### ISSUE TITLE
It works but I can not see anything on the map?

### ISSUE THREAD

**Issue by xDyN** [Noctem/pokeminer#3]
![image](https://cloud.githubusercontent.com/assets/22619864/21183602/8daee79c-c1bd-11e6-95b6-2959efc98c8d.png)

**Comment by xDyN** [comment]
i can see gym but i can't see poketop and pokemon 
![image](https://cloud.githubusercontent.com/assets/22619864/21192680/f9bebfae-c25b-11e6-93c1-afe195c76b5c.png)

**Comment by Noctem** [comment]
Sorry for the delay in getting back to you. Are you seeing Pokémon yet? For now, it is normal to not see Pokémon when you're first getting started since it only displays Pokémon with known expiration times (either from getting a valid timestamp or knowing the spawn's cycle). I will be implementing displaying Pokémon with unknown expiration times soon.

Displaying Pokéstops on the map has also not been implemented yet, but it is on my to-do list.

**Comment by Noctem** [comment]
Closing since I haven't heard back. Feel free to reopen if you're still experiencing this.
